# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

resources:
  repositories:
  - repository: templates
    type: github
    endpoint: jpfrezzarin
    name: jpfrezzarin/azure-pipeline-templates

trigger:
- main

pool:
  vmImage: 'ubuntu-18.04'

stages:
  - stage: build_publish
    displayName: build and publish
    jobs:
      - job: build_dev
        displayName: build and publish - dev
        steps:
        - template: dotnet-core/dotnet-core-build-publish-with-sonar.yml@templates
          parameters:
            environment: 'dev'
            buildConfiguration: 'Debug'
            artifactName: 'app.dev'
            sonarEndpoint: 'jpfrezzarin-sonarcloud'
            sonarOrganization: 'jpfrezzarin'
            sonarProjectKey: 'jpfrezzarin.net-5-web-api'
            sonarProjectName: 'net-5-web-api'

      - job: build_prd
        displayName: build and publish - prd
        dependsOn: build_dev
        steps:
        - template: dotnet-core/dotnet-core-build-publish.yml@templates
          parameters:
            environment: 'prd'
            buildConfiguration: 'Release'
            artifactName: 'app.prd'