# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

resources:
  repositories:
  - repository: templates
    type: github
    endpoint: jpfrezzarin
    name: jpfrezzarin/azure-pipeline-templates

trigger:
- main

pool:
  vmImage: 'ubuntu-18.04'

stages:
  - stage: build
    displayName: build
    jobs:
      - template: dotnet-core/dotnet-core-build-publish-with-sonar.yml@templates
        parameters:
          environment: 'dev'
          dotnetVersion: '5.0.x'
          sonarEndpoint: 'jpfrezzarin-sonarcloud'
          sonarOrganization: 'jpfrezzarin'
          sonarProjectKey: 'jpfrezzarin.net-5-web-api'
          sonarProjectName: 'net-5-web-api'
          buildConfiguration: 'Debug'
          artifactName: 'app.dev'

      - template: dotnet-core/dotnet-core-build-publish.yml@templates
        parameters:
          environment: 'prd'
          dotnetVersion: '5.0.x'
          buildConfiguration: 'Release'
          artifactName: 'app.prd'