# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: 'ubuntu-18.04'

stages:
  - stage: build
    displayName: Build stage
    jobs:
      - template: templates/dotnet-build-publish.yml
        parameters:
          environment: 'dev'
          dotnetVersion: '5.0.x'